// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJGGhRF3B-rArv61RgciCsYigG6fzDt3A',
    appId: '1:119257014191:android:a7560243911f6b540a595a',
    messagingSenderId: '119257014191',
    projectId: 'meeem-test',
    storageBucket: 'meeem-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIeG1U3F22QdOjlxDlVzZjBGlm9r4L3PA',
    appId: '1:119257014191:ios:eadab529cb4b425c0a595a',
    messagingSenderId: '119257014191',
    projectId: 'meeem-test',
    storageBucket: 'meeem-test.firebasestorage.app',
    androidClientId: '119257014191-6id1fn24nni60l2lor5plp267dpar4jh.apps.googleusercontent.com',
    iosClientId: '119257014191-5omatcl27696tcolvl3o33anrdq2ucrl.apps.googleusercontent.com',
    iosBundleId: 'com.meeem.rider.meeemRider',
  );
}
